---

- name: Prepare
  hosts: bastion
  gather_facts: false
  tasks:

    - name: Install sshpass
      local_action:
        module: apt
        name: sshpass
      become: true
      run_once: true

    - name: Ensure known_hosts are set
      local_action:
        module: blockinfile
        path: ~/.ssh/known_hosts
        create: yes
        state: present
        block: "{{ lookup('pipe', 'ssh-keyscan '+inventory_hostname) }}"
      run_once: true
      
- name: Bootstrap Bastion
  hosts: bastion
  become: true

  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

    - name: System update
      apt:
        name: "*"
        state: latest
        update_cache: true
        cache_valid_time: 3600

    - name: "Set hostname to {{ bastion_hostname }}"
      hostname:
        name: "{{ bastion_hostname }}"

  roles:
    - role: ckaserer.dhcpcd
      vars:
        dhcpcd_interface: "{{ bastion_dhcpcd_interface }}"
        dhcpcd_ip_address: "{{ bastion_dhcpcd_ip_address }}"
        reboot: "{{ bastion_dhcpcd_reboot }}"
    - role: ckaserer.k3s_iptables
    - role: bertvv.bind
    - role: ckaserer.dhcp
    - role: ckaserer.haproxy

...
