---

- name: Prepare
  hosts: bastion
  gather_facts: false
  become: true
  tasks:

    - name: Install sshpass
      local_action:
        module: apt
        name: sshpass
      run_once: True

    - name: Ensure known_hosts are set
      local_action:
        module: lineinfile
        dest: ~/.ssh/known_hosts
        create: yes
        state: present
        line: "{{ lookup('pipe', 'ssh-keyscan -t rsa '+inventory_hostname) }}"
        regexp: "^{{ inventory_hostname }}"
      run_once: true

- name: Known hosts
  hosts: bastion
  gather_facts: false
      
- name: Bootstrap Bastion
  hosts: bastion
  become: true

  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

    - name: "Set hostname to {{ bastion_hostname }}"
      hostname:
        name: "{{ bastion_hostname }}"
      tags:
        - notest

  roles:
    - role: ckaserer.dhcpcd
      vars:
        dhcpcd_interface: "{{ bastion_dhcpcd_interface }}"
        dhcpcd_ip_address: "{{ bastion_dhcpcd_ip_address }}"
        reboot: "{{ bastion_dhcpcd_reboot }}"
      tags:
        - notest
    - role: ckaserer.k3s_iptables
      tags:
        - notest
    - role: bertvv.bind
    - role: ckaserer.dhcp
    - role: ckaserer.haproxy

...
